name: CI
on: [push, pull_request]

jobs:

  build:
    name: runner / build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: "make build"

  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Unit Tests
        run: "make test"
